/*
========================================================================================================
Name : 24
Author : Aaradhya GHota
Description : Write a program to create a message queue and print the key and message queue id.
Date: 14 Sept, 2024.
========================================================================================================
*/

#include <stdio.h>
#include <sys/ipc.h>
#include <sys/msg.h>
#include <stdlib.h>

int main(){
        //ftok() (file to key)  generates a unique key that identifies an IPC resource like a message queue, semaphore, or shared memory segment. 
	int k = ftok(".", 1);
	//key_t ftok(const char *pathname, int proj_id);//key_t is 32 bit unique key generated by combining: inode number ,device ID ,project identifier 
                                          //between 0 and 255
	if(k == -1){
		perror("Ftok Error");
		exit(1);
	}
	//If the file "xyz" or directory "." does not exist, ftok() will return -1. Always ensure the file exists and the process has access to it.
	printf("Key: %d\n", k);
	
	
        //msgget()  create a new message queue or access an existing one using the provided key in the given permission 0666.
	int mqid = msgget(k, 0666 | IPC_CREAT);// IPC_CREAT is used to create the message queue if it does not already exist.
	if (mqid == -1){
		perror("Msgget Error");
		exit(1);
	}
	printf("Message Queue ID: %d\n", mqid);
}

/*
========================================================================================================
Output:

./a.out
Key: 17206610
Message Queue ID: 0

========================================================================================================
*/
