#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS

// LOGIN
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password:"
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT_BAE "666"

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear admin! With great power comes great responsibility!\nEnter your credentials to unlock this power!"
#define ADMIN_LOGIN_SUCCESS "----------------Welcome Admin-------------------"

#define ADMIN_LOGOUT "Logging you out now admin! Good bye!^"
#define ADMIN_EXIT "Admin exiting!$"

// ERROR
#define ADMIN_ID_DOESNT_EXIT "No admin could be found for the given ID"
#define ADMIN_LOGIN_ID_DOESNT_EXIT "No admin could be found for the given login ID$"

// ADMIN MENU
#define ADMIN_MENU                                                             \
    "1. Add New Bank Employee\n2. Modify Customer Details\n3. Modify Employee" \
    "details\n4. Manage User Role\n5. Change Password\n6. Logout \n "          \
    "Press any other key to exit"

// ERROR

#define ERRON_INPUT_FOR_NUMBER                                            \
    "It seems you have passed a sequence of alphabets when a number was " \
    "expected or you have entered an invalid number!\nYou'll now be "     \
    "redirected to the main menu!^"

// ADMIN ADD EMPLOYEE
#define ADMIN_ADD_EMPLOYEE "Enter the details for the employee\n"
#define ADMIN_ADD_EMPLOYEE_NAME "What is the employee's name?"
#define ADMIN_ADD_EMPLOYEE_GENDER "What is the employee's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_EMPLOYEE_ROLE "What is the employee's role? \nEnter M for manager and E for employee"
#define ADMIN_ADD_EMPLOYEE_AGE "What is the employee's age?"
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_LOGIN "The autogenerated login ID for the employee is : "
#define AUTOGEN_PASSWORD "defaultPassword"  // append to end of next string macro
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_PASSWORD "The autogenerated password for the employee is : "
#define ADMIN_ADD_EMPLOYEE_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"
#define ADMIN_ADD_EMPLOYEE_WRONG_ROLE "It seems you'va entered a wrong choice!\nYou'll now be redirected to main menu!^"
// ADMIN MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_CUSTOMER_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define ADMIN_MOD_CUSTOMER_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "What's the updated value for age?"
#define ADMIN_MANG_EMPLOYEE_ROLE "Enter the ID of the employee who's role you want to edit"
#define ADMIN_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

// ADMIN MODIFY EMPLOYEE INFO
#define ADMIN_MOD_EMPLOYEE_ID "Enter the ID of the employee who's information you want to edit"
#define ADMIN_MOD_EMPLOYEE_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define ADMIN_MOD_EMPLOYEE_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_EMPLOYEE_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_EMPLOYEE_NEW_AGE "What's the updated value for age?"
// #define ADMIN_MANG_EMPLOYEE_ROLE "Enter the ID of the employee who's role you want to edit"
#define ADMIN_MOD_EMPLOYEE_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

// MANAGER

// LOGIN WELCOME
#define MANAGER_LOGIN_WELCOME "Welcome dear manager! Enter your credentials to gain access to your account!"
#define MANAGER_LOGIN_SUCCESS "-----------Welcome manager-------------------"
#define MANAGER_LOGOUT "Logging you out now dear manager! Good bye!^"
#define MANAGER_EXIT "Manager exiting!!$"
#define MANAGER_ACTIVE_CUSTOMER "Enter the Id of the customer who's account status you want to change"
#define MANAGER_ADD_CUSTOMER_WRONG_STATUS "Entered status of account is invalid !^"

// MANaGER MENU
#define MANAGER_MENU                                      \
    "1. Activate/Deactivate Customer Accounts \n"         \
    "2. View all the unassigned Loans\n"                  \
    "3. Assign Loan Application Processes to Employees\n" \
    "4. Review Customer Feedback\n"                       \
    "5. Change Password\n"                                \
    "6. Logout\n"                                         \
    "Press any other key to exit"

// ====================================================

// ========== EMPLOYEE SPECIFIC TEXT===================

// LOGIN WELCOME
#define EMPLOYEE_LOGIN_WELCOME "Welcome dear employee! Enter your credentials to gain access to your account!"
#define EMPLOYEE_LOGIN_SUCCESS "-----------Welcome employee-------------------"
#define EMPLOYEE_LOGOUT "Logging you out now dear employee! Good bye!^"
#define EMPLOYEE_EXIT "Employee exiting!!$"

#define EMPLOYEE_ID_DOESNT_EXIT "No employee could be found for the given ID"
#define EMPLOYEE_LOGIN_ID_DOESNT_EXIT "No employee could be found for the given login ID$"

// EMPLOYEE MENU
#define EMPLOYEE_MENU                        \
    "1. Add new Customer \n"                 \
    "2. Modify Customer Details\n"           \
    "3. Appove / Reject Loan Applications\n" \
    "4. View Assgined Loan Applications\n"   \
    "5. Show passbook of customer\n"         \
    "6. Change Password\n"                   \
    "7. Logout\n"                            \
    "Press any other key to exit"

// EMPLOYEE ADD EMPLOYEE
#define EMPLOYEE_ADD_CUSTOMER "Enter the details for the customer\n"
#define EMPLOYEE_ADD_CUSTOMER_NAME "What is the customer's name?"
#define EMPLOYEE_ADD_CUSTOMER_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define EMPLOYEE_ADD_CUSTOMER_AGE "What is the customer's age?"
#define EMPLOYEE_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "defaultPassword"  // append to end of next string macro
#define EMPLOYEE_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define EMPLOYEE_AUTOGEN_ACCOUNTNO "The autogenerated account no. for customer is :"
#define EMPLOYEE_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"

// ERROR
#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"
#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID$"
//

// CUSTOMER

#define CUSTOMER_LOGIN_WELCOME                                              \
    "Welcome dear customer! Enter your credentials to gain access to your " \
    "account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome beloved customer!"

#define CUSTOMER_LOGOUT "Logging you out now dear customer! Good bye!^"
#define CUSTOMER_EXIT "Customer Exitting !!$"

#define CUSTOMER_ADD_LOAN "Enter the amount to apply for a loan : "
#define CUSTOMER_ADD_FEEDBACK "Enter feedback : "
// Customer MENU
#define CUSTOMER_MENU                             \
    "1. VIew Account Balance\n"                   \
    "2. Deposit Money\n"                          \
    "3. Withdraw Money\n"                         \
    "4. Transfer funds\n"                         \
    "5. Apply for a Loan\n"                       \
    "6. Change Password\n"                        \
    "7. Add Feedback\n"                           \
    "8. Enter Trasaction ID to see Transaction\n" \
    "9. Veiw Transation History\n"                \
    "10. Logout\n"                                \
    "Press any other key to exit"

#define GET_ACCOUNT_NUMBER "Enter the account number of the account you're searching for"
#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number"

#define ACCOUNT_DEACTIVATED "It seems your account has been deactivated!^"

#define DEPOSIT_AMOUNT "How much is it that you want to add into your bank?"
#define DEPOSIT_AMOUNT_INVALID "You seem to have passed an invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS \
    "The specified amount has been successfully added to your bank account!^"

#define TRANSFER_AMOUNT_INVALID "You seem to have passed an invalid amount or you dont have this much balance in your account!^ "
#define TRANSFER_AMOUNT_SUCCESS \
    "The specified amount has been successfully added to your bank account!^"

#define WITHDRAW_AMOUNT \
    "How much is it that you want to withdraw from your bank?"
#define WITHDRAW_AMOUNT_INVALID                                           \
    "You seem to have either passed an invalid amount or you don't have " \
    "enough money in your bank to withdraw the specified amount^"
#define WITHDRAW_AMOUNT_SUCCESS                                            \
    "The specified amount has been successfully withdrawn from your bank " \
    "account!^"

#define AMOUNT_TRANSFER "Enter the amount you want to Transfer:"
#define ACOUNT_TRANSFER "Enter account no. to which you want to transfer:"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID \
    "The entered password doesn't seem to match with the old password!^"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID \
    "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

#define TRANSACTION_ID_DOESNT_EXIT "this Transaction id doesn't exist!$"
#define TRANSACTION_NOT_ACCESSABLE "Trying to access wrong Transaction ID !$"
#define ENTER_TRANCTION_ID "Enter the Transaction Id which you want to see : "
//
#define CUSTOMER_FILE "./records/customer.txt"
#define EMPLOYEE_FILE "./records/employee.txt"
#define TRANSACTION_FILE "./records/transactions.txt"
#define ADMIN_FILE "./records/admin.txt"
#define FEEDBACK_FILE "./records/feedback.txt"
#define LOAN_FILE "./records/loan.txt"

#endif